### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by zeroeightysix** [subgraph/gtk-layer-shell-rs#1]
Attempting to run the example will error:
```
error: failed to run custom build command for `gtk-layer-shell-sys v0.0.1 (/home/ridan/gtk-layer-shell-rs/gtk-layer-shell-sys)`

Caused by:
  process didn't exit successfully: `/home/ridan/gtk-layer-shell-rs/target/debug/build/gtk-layer-shell-sys-d0cb0770ffc0b86c/build-script-build` (exit code: 1)
--- stderr
`"pkg-config" "--libs" "--cflags" "gtk-layer-shell-0" "gtk-layer-shell-0 >= 0.1"` did not exit successfully: exit code: 1
--- stderr
Package gtk-layer-shell-0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk-layer-shell-0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gtk-layer-shell-0', required by 'virtual:world', not found
Package 'gtk-layer-shell-0', required by 'virtual:world', not found
```
I installed gtk-layer-shell as instructed in its README.

I can check the library exists using `ldconfig`:
```
$ ldconfig -p | grep -i gtk-layer
	libgtk-layer-shell.so (libc6,x86-64) => /usr/local/lib/libgtk-layer-shell.so
``` 
`gtk-layer-demo` and `gtk-layer-example` work perfectly.

How do I fix this issue?

**Comment by mckinney-subgraph** [comment]
It looks like the Rust compiler is not searching `/usr/local/lib` for the `.so` file. There are a few approaches to solve this.

1. Change the install prefix for `gtk-layer-shell` so that it points to `/usr`, ex:
```bash
$ meson --prefix="/usr" build
```

2. If you still want to use `/usr/local/lib` then you can update your library search path, see: https://stackoverflow.com/questions/4743233/is-usr-local-lib-searched-for-shared-libraries

**Comment by zeroeightysix** [comment]
The first option worked. Thanks!
