### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by cjbassi** [subgraph/gtk-layer-shell-rs#3]
Would it be possible to publish this package to crates.io? Thanks!

**Comment by rkanati** [comment]
ping @mckinney-subgraph, this would be nice to have on crates.

**Comment by mckinney-subgraph** [comment]
Yup, noted, I will do this soon. Thanks for the reminder!

**Comment by mckinney-subgraph** [comment]
I am going to close this request because there are some alternatives that are available on crates.io and elsewhere. Those alternatives may be better maintained or provide a better experience across different versions of `GTK` and `gtk-layer-shell`, ex: handling *-sys conflicts, more up-to-date, etc. Since I use the bindings internally and they work for me as-is, I don't update them very much. Some other people use them from git directly or by vendoring them/dealing with *-sys probz themselves, so that is cool. I'll happily accept PRs to make these bindings better but I don't really plan to put them onto crates.io under a different name and provide support.
